---
collections:
  - name: openstack.cloud
    version: ">=2.5.0"
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: community.libvirt
    version: ">=1.3.0"
  - name: openvswitch.openvswitch
    version: ">=2.1.0"
