---
- name: Create OVE node trunks
  ansible.builtin.include_tasks: create_trunk.yml
  loop: "{{ range(0, ove_node_count | int) | product([0, 1]) | list }}"
  loop_control:
    loop_var: node_trunk_pair
  vars:
    node_idx: "{{ node_trunk_pair[0] }}"
    trunk_idx: "{{ node_trunk_pair[1] }}"

- name: Create OVE nodes (agent ISO method)
  ansible.builtin.include_tasks: create_ove_nodes.yml
  when: install_method == 'ove'

- name: Create appliance nodes (factory imaging method)
  ansible.builtin.include_tasks: create_appliance_nodes.yml
  when: install_method == 'appliance'
