---
- name: restart named
  ansible.builtin.systemd:
    name: named
    state: restarted

- name: restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: restart sushy-emulators
  ansible.builtin.systemd:
    name: sushy-emulators
    daemon_reload: true
    state: restarted
