---
- name: Install ansible-core
  ansible.builtin.dnf:
    name: ansible-core
    state: present

- name: Install community.general Ansible collection
  ansible.builtin.command:
    cmd: ansible-galaxy collection install community.general
  changed_when: false

- name: Sync OVE agent ISO to web root
  ansible.posix.synchronize:
    src: "{{ ove_agent_iso_path }}"
    dest: "/var/www/html/{{ ove_agent_iso_path | basename }}"
    mode: push

- name: Template Redfish inventory
  ansible.builtin.template:
    src: ove-redfish-inventory.ini.j2
    dest: /root/ove-redfish-inventory.ini
    mode: "0644"

- name: Template boot playbook
  ansible.builtin.template:
    src: boot-ove-nodes.yml.j2
    dest: /root/boot-ove-nodes.yml
    mode: "0644"
