---
- name: Set cloud-user console password
  ansible.builtin.shell:
    cmd: echo 'cloud-user:{{ bastion_console_password }}' | chpasswd
  become: true
  no_log: "{{ not debug_mode | default(false) | bool }}"
  changed_when: true
