---
- name: Install GNOME desktop environment
  ansible.builtin.dnf:
    name: "@workstation"
    state: present

- name: Set default target to graphical
  ansible.builtin.systemd:
    name: graphical.target
    enabled: true

- name: Set graphical as default systemd target
  ansible.builtin.command:
    cmd: systemctl set-default graphical.target
  changed_when: true
