---
- name: Install GNOME desktop environment and podman
  ansible.builtin.dnf:
    name:
      - "@workstation"
      - podman
    state: present

- name: Set graphical as default systemd target
  ansible.builtin.command:
    cmd: systemctl set-default graphical.target
  changed_when: true

- name: Start graphical target
  ansible.builtin.systemd:
    name: graphical.target
    state: started
