---
- name: Install Apache httpd
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Allow HTTP on management interface
  ansible.posix.firewalld:
    service: http
    zone: trusted
    permanent: true
    immediate: true
    state: enabled

- name: Start and enable httpd
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true
