---
- name: Generate SSH key for cloud-user
  ansible.builtin.include_tasks: ssh_key.yml

- name: Configure bastion mgmt interface statically (libvirt backend)
  ansible.builtin.include_tasks: mgmt_iface.yml
  when: infra_backend | default('openstack') == 'libvirt'

- name: Register with RHSM
  ansible.builtin.include_tasks: subscription.yml

- name: Configure GNOME desktop
  ansible.builtin.include_tasks: desktop.yml

- name: Configure firewall (no IP forwarding)
  ansible.builtin.include_tasks: firewall.yml

- name: Configure BIND DNS
  ansible.builtin.include_tasks: dns.yml

- name: Configure Chrony NTP server
  ansible.builtin.include_tasks: ntp.yml

- name: Configure sushy-emulator
  ansible.builtin.include_tasks: sushy.yml
  when: infra_backend | default('openstack') == 'openstack'

