---
# Role-specific variables (all others defined in inventory/group_vars/all.yml)
# Appliance image location on KVM host (set by pre_tasks or appliance_image role)
appliance_image_on_kvm: "{{ libvirt_pool_path }}/appliance-base.raw"

# Role state
state: present
